# Generated by Django 2.1.4 on 2019-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20190125_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
