# Generated by Django 2.1.4 on 2019-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_society_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='society_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
