# Generated by Django 2.1.5 on 2019-01-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0004_auto_20190128_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='members',
        ),
    ]
