# Generated by Django 2.1.5 on 2019-01-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_password_changed'),
        ('society', '0005_remove_society_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocietyMemberRelationShip',
            new_name='JoinSocietyRequest',
        ),
    ]
