# Generated by Django 2.1.5 on 2019-01-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_password_changed'),
        ('society', '0006_auto_20190129_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
