# Generated by Django 2.1.4 on 2019-02-04 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_auto_20190204_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joinsocietyrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinsocietyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='members',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='society',
            name='tags',
            field=models.ManyToManyField(blank=True, to='society.SocietyTag'),
        ),
    ]
