# Generated by Django 2.1.4 on 2019-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0010_auto_20190204_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='credit',
            field=models.PositiveSmallIntegerField(default=0, help_text='The maximum count of credit receivers(not maximum credits).'),
        ),
    ]
