# Generated by Django 2.1.4 on 2019-02-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0011_auto_20190209_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityrequest',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_requests', to='society.Society'),
        ),
    ]
