# Generated by Django 2.1.4 on 2019-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0014_remove_society_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='president_grade',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
