# Generated by Django 2.1.4 on 2019-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0017_auto_20190224_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='activity_place',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='activity_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='mentor',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='society',
            name='special_room',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
