# Generated by Django 2.1.4 on 2019-03-21 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society_bureau', '0004_societybureau_phone'),
        ('society', '0018_auto_20190303_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_societies', to='society_bureau.SocietyBureau'),
        ),
        migrations.AddField(
            model_name='society',
            name='president_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
