# Generated by Django 2.1.4 on 2019-02-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society_bureau', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societybureau',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='society_bureau', to=settings.AUTH_USER_MODEL),
        ),
    ]
