# Generated by Django 2.1.4 on 2019-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_bureau', '0003_auto_20190209_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='societybureau',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
