# Generated by Django 2.1.4 on 2019-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
