# Generated by Django 2.2.9 on 2020-02-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0019_auto_20190321_0325'),
        ('student', '0005_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('credit', models.PositiveSmallIntegerField(default=1, help_text='可获得学分的人数的最大值')),
                ('open', models.BooleanField(default=True)),
                ('receivers', models.ManyToManyField(blank=True, default=None, related_name='receive_credit_from', to='student.Student')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributed_credit', to='society.Society')),
            ],
        ),
        migrations.AddConstraint(
            model_name='creditdistribution',
            constraint=models.UniqueConstraint(fields=('society', 'year', 'semester'), name='unique_credit_distribution'),
        ),
    ]
