# Generated by Django 2.1.4 on 2019-02-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0009_auto_20190204_1119'),
        ('student', '0003_student_password_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReceivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('receivers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='society.Society')),
            ],
        ),
    ]
