# Generated by Django 2.1.4 on 2019-02-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditreceivers',
            name='receivers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student'),
        ),
    ]
