# Generated by Django 2.1.4 on 2019-02-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0011_auto_20190209_1514'),
        ('society_manage', '0002_auto_20190210_1219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditreceivers',
            unique_together={('society', 'year', 'semester')},
        ),
    ]
