# Generated by Django 2.1.4 on 2019-02-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_password_changed'),
        ('society_manage', '0003_auto_20190210_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditreceivers',
            name='receivers',
        ),
        migrations.AddField(
            model_name='creditreceivers',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='credit_givers', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='creditreceivers',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_receivers', to='society.Society'),
        ),
    ]
