# Generated by Django 2.1.4 on 2019-02-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_manage', '0004_auto_20190210_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditreceivers',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
