# Generated by Django 2.1.7 on 2019-02-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0014_remove_society_credit'),
        ('student', '0003_student_password_changed'),
        ('society_manage', '0004_auto_20190210_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('credit', models.PositiveSmallIntegerField(help_text='可获得学分的人数的最大值')),
                ('receivers', models.ManyToManyField(blank=True, default=None, related_name='receive_credit_from', to='student.Student')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='distributed_credit', to='society.Society')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='creditreceivers',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='creditreceivers',
            name='receivers',
        ),
        migrations.RemoveField(
            model_name='creditreceivers',
            name='society',
        ),
        migrations.DeleteModel(
            name='CreditReceivers',
        ),
        migrations.AlterUniqueTogether(
            name='creditdistribution',
            unique_together={('society', 'year', 'semester')},
        ),
    ]
