# Generated by Django 2.1.7 on 2019-02-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_manage', '0005_auto_20190214_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdistribution',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creditdistribution',
            name='credit',
            field=models.PositiveSmallIntegerField(default=1, help_text='可获得学分的人数的最大值'),
        ),
    ]
