# Generated by Django 2.1.7 on 2019-08-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_manage', '0006_auto_20190214_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdistribution',
            name='closed',
        ),
        migrations.AddField(
            model_name='creditdistribution',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
