# Generated by Django 2.1.7 on 2019-08-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_manage', '0007_auto_20190801_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditdistribution',
            old_name='opened',
            new_name='open',
        ),
    ]
